spring:
  application:
    name: lab4
  security:
    jwt:
      secret:
        refresh_token: "test"
        access_token: "test233"
  datasource:
    url: jdbc:postgresql://localhost:5432/lab3
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        id:
          new_generator_mappings: true
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
server:
  port: 8080


